var mongoose = require('mongoose');
var uniqueValidator = require('mongoose-unique-validator');
var bcrypt = require('bcrypt');

var AccessSchema = new mongoose.Schema({
  _firstName: {
    type: String,
    required: true
  },
  _lastName: {
    type: String,
    required: true
  },
    _accessCode: {  //unique code generated by admin upon adding new student will be student's id
    type: String,
    required: true
  }
});

/*
this didn't work, not sure how to implement methods/functions with mongoose schema
AccessSchema.methods.verifyAccessCode = function(code) {
    console.log("verifying access code..");
    AccessSchema.findOne({_accessCode: code}, function (next) {
      if (err) {
        console.log(err);
        return next(err);
      }
      console.log(code);
      next();
    });
}
*/


//Creating model AccessUser from AcessSchema to verify code in AccessCodes collection
var AccessUser = mongoose.model('Access User', AccessSchema, 'Access_Codes');

module.exports = AccessUser
