
var mongoose = require('mongoose');
//var uniqueValidator = require('mongoose-unique-validator');
var bcrypt = require('bcrypt');

// define the schema for new students
var StudentSchema = new mongoose.Schema({
  /*
  _id: {  //unique code generated by admin upon adding new student will be student's id
    type: String,
    //unique: true, //unique validator applied here
    required: true
  },
  */
  _firstName: {
    type: String,
    required: true
  },
  _lastName: {
    type: String,
    required: true
  },
  _dob: { // may not be able to store this in actuality due to it being private data
    type: String,
    required: true
  },
  _address: {
    type: String,
    required: true
  },
  _contactName: {
    type: String,
    required: true
  },
  _contactPhone: {
    type: String,
    required: true
  },
  _belt: {
    type: String,
    required: true
  },
  _publicNotes: {
    type: String
  },
  _privateNotes: {
    type: String
  }
});



// Apply the uniqueValidator plugin to StudentSchema.
//StudentSchema.plugin(uniqueValidator);

//Creating model NewUser from RegisterSchema
var NewStudent = mongoose.model('New Student', StudentSchema, 'User Info')

//Instantiating user from NewUser
//var newStudent = new NewStudent();

module.exports = NewStudent
